name: m3e_collection
description: Aggregated exports of all Material 3 Expressive components for Flutter.
version: 0.3.6
repository: https://github.com/EmilyMoonstone/material_3_expressive/tree/main/packages/m3e_collection
issue_tracker: https://github.com/EmilyMonestone/material_3_expressive/issues

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  app_bar_m3e: ^0.1.2
  button_group_m3e: ^0.3.0
  button_m3e: ^0.1.2
  expressive_refresh: ^0.1.2
  fab_m3e: ^0.1.1
  flutter:
    sdk: flutter
  icon_button_m3e: ^0.2.1
  loading_indicator_m3e: ^0.1.1
  m3e_design: ^0.2.1
  material_new_shapes: ^1.0.0
  navigation_bar_m3e: ^0.1.1
  navigation_rail_m3e: ^0.3.5
  progress_indicator_m3e: ^0.1.1
  slider_m3e: ^0.1.1
  split_button_m3e: ^0.2.1
  toolbar_m3e: ^0.1.1

